//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryDesigner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoryDesigner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find image .
        /// </summary>
        internal static string cannotFindImage {
            get {
                return ResourceManager.GetString("cannotFindImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version: {0}
        ///Update Version: {1}.
        /// </summary>
        internal static string currUpdVersion {
            get {
                return ResourceManager.GetString("currUpdVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deepmap.
        /// </summary>
        internal static string Deepmap {
            get {
                return ResourceManager.GetString("Deepmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FX Shapes.
        /// </summary>
        internal static string FXShapes {
            get {
                return ResourceManager.GetString("FXShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game was created under .
        /// </summary>
        internal static string gameCreatedUnder {
            get {
                return ResourceManager.GetString("gameCreatedUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project was imported to {0}..
        /// </summary>
        internal static string importAdz {
            get {
                return ResourceManager.GetString("importAdz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventoryfield.
        /// </summary>
        internal static string Inventoryfield {
            get {
                return ResourceManager.GetString("Inventoryfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Story Designer..
        /// </summary>
        internal static string languageSwitch {
            get {
                return ResourceManager.GetString("languageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version: {0}.
        /// </summary>
        internal static string newVersion {
            get {
                return ResourceManager.GetString("newVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        internal static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        ///Start now?.
        /// </summary>
        internal static string startNow {
            get {
                return ResourceManager.GetString("startNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Update available.
        /// </summary>
        internal static string updateAvail {
            get {
                return ResourceManager.GetString("updateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update download was cancelled.
        ///This program has not been modified..
        /// </summary>
        internal static string updateCancelled {
            get {
                return ResourceManager.GetString("updateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem downloading the update.
        ///Please try again later..
        /// </summary>
        internal static string updateError {
            get {
                return ResourceManager.GetString("updateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update previously created game?.
        /// </summary>
        internal static string updatePrevious {
            get {
                return ResourceManager.GetString("updatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Download....
        /// </summary>
        internal static string veryfingDownload {
            get {
                return ResourceManager.GetString("veryfingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkmap.
        /// </summary>
        internal static string Walkmap {
            get {
                return ResourceManager.GetString("Walkmap", resourceCulture);
            }
        }
    }
}
