#ifndef FUNCIDS_H
#define FUNCIDS_H

enum Functions{
  WGLCHOOSEPIXELFORMAT,
  WGLCREATECONTEXT,
  WGLDELETECONTEXT,
  WGLDESCRIBEPIXELFORMAT,
  WGLGETPIXELFORMAT,
  WGLMAKECURRENT,
  WGLSETPIXELFORMAT,
  WGLSHARELISTS,
  WGLSWAPBUFFERS,
};

#endif
