#ifndef FUNCIDS_H
#define FUNCIDS_H

enum Functions{
  EGLCHOOSECONFIG,
  EGLCREATECONTEXT,
  EGLCREATEWINDOWSURFACE,
  EGLDESTROYCONTEXT,
  EGLDESTROYSURFACE,
  EGLGETCONFIGATTRIB,  
  EGLGETDISPLAY,
  EGLGETERROR,
  EGLINITIALIZE,
  EGLMAKECURRENT,
  EGLQUERYSURFACE,
  EGLSWAPBUFFERS,
  EGLTERMINATE,

  WGLCHOOSEPIXELFORMAT,
  WGLCREATECONTEXT,
  WGLDELETECONTEXT,
  WGLDESCRIBEPIXELFORMAT,
  WGLGETPIXELFORMAT,
  WGLMAKECURRENT,
  WGLSETPIXELFORMAT,
  WGLSHARELISTS,
  WGLSWAPBUFFERS,
};

#endif
