cd ..\HQClient
..\..\..\..\build_win\heroquest\HQEditor\Debug\HQEditor.exe ..\HQEditor\basic\maze.map
HQEditor basic\trial.map
HQEditor basic\rescueSirRagnar.map
HQEditor basic\lairOrcWarlord.map
HQEditor basic\princeMagnusGold.map
HQEditor basic\melarsMaze.map
HQEditor basic\LegacyOrcWarlord.map
HQEditor basic\lostWizard.map
HQEditor basic\fireMage.map
HQEditor basic\raceAgainstTime.map
HQEditor basic\castleMystery.map
HQEditor basic\bastionChaos.map
HQEditor basic\barakTor.map
HQEditor basic\spiritBlade.map
HQEditor basic\returnBarakTor.map